/*	This include file contains the link list functions
	developed in Chapter 15.
	   Written by: 
	   Date:  
*/
#ifndef LINK_HEADER
   #define LINK_HEADER

//	Include Files for Functions        
#include "P15-01.c"      // Insert     
#include "P15-02.c"      // Delete     
#include "P15-03.c"      // Search a Linear List  
#include "P15-04.c"      // Print Linear List
#include "P15-05.c"      // Average Llinear List
#include "P15-06.c"      // Build List
#include "P15-07.c"      // Delete Key 
#include "P15-getData.c" // Get Data (Not in text)
#endif
